Models/ErrorViewModel.cs
namespace AspcoreMvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ExampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspcoreMvc.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ExampleController : ControllerBase
    {
        // GET: api/Example
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET: api/Example/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/Example
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT: api/Example/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/Example/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

Controllers/FilesController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspcoreMvc.Controllers
{
    public class FilesController : Controller
    {
        public IActionResult Index()
        {
            string[] files = Directory.GetFiles("./TextFiles").Select(file => Path.GetFileNameWithoutExtension(file)).ToArray();
            return View(files);
        }

        public IActionResult ContentRead(string id)
        {
            StreamReader sr = System.IO.File.OpenText("./TextFiles/" + id + ".txt");
            string strContents = sr.ReadToEnd();
            ViewBag.Content = strContents;
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspcoreMvc.Models;

namespace AspcoreMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        string[] days = { "M", "T", "W" };
        ViewData["days"] = days;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Bogus()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspcoreMvc.Controllers
{
    public class ProcessController : Controller
    {
        // GET: Process
        public ActionResult Index()
        {
            Process[] procs = Process.GetProcesses();
            ViewBag.Procs = procs;
            return View(Process.GetProcesses());
        }

        public IActionResult Display(int id)
        {
            Process osProcess = Process.GetProcessById(id);
            return View(osProcess);
        }
    }
}

Views/Files/ContentRead.cshtml
@{
    ViewData["Title"] = "Content";
    string content = ViewBag.Content;
}

<h1>Content</h1>

<p>@content</p>

Views/Files/Index.cshtml
@model string[]
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<ul>
    @foreach (var item in Model)
    {
        <li><a asp-controller="Files" asp-action="ContentRead" asp-route-id="@item">@item</a></li>
    }
</ul>

Views/Home/Bogus.cshtml
@{
    ViewData["Title"] = "Bogus";
}

<h1>Bogus</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    string[]? days = (string[])ViewData["days"]!;
}

<div class="text-center">
    <h1 class="display-4" style="color: tomato;">Welcome to Comp 4870</h1>
    <h2>Man Sun</h2>
    <h2>A01074365</h2>
    <h2>I want to be a software developer</h2>
</div>

Views/Process/Display.cshtml
@model System.Diagnostics.Process
@{
    ViewData["Title"] = "Display";
}

<h1>Display</h1>

<div>
    <table>
        <th>
            id
        </th>
        <th>name</th>
        <th>count</th>
        <tr>

        </tr>
    </table>
</div>

Views/Process/Index.cshtml
@model System.Diagnostics.Process[]
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<ul>
    @foreach (var item in Model)
    {
        <li><a asp-controller="Process" asp-action="Display" asp-route-id="@item.Id">@item.ProcessName</a></li>
    }
</ul>

Views/Process/Process.cshtml
@{
    ViewData["Title"] = "Process";
}

<h1>Process</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspcoreMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspcoreMvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspcoreMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bogus">Bogus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Process"
                                asp-action="Index">Process</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files"
                                asp-action="Index">Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspcoreMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>